if

diff --git a/.github/workflows/create-issue.yml b/.github/workflows/create-issue.yml
--- a/.github/workflows/create-issue.yml
+++ b/.github/workflows/create-issue.yml
@@ -8,20 +8,24 @@ on:
   workflow_dispatch:
 
 jobs:
-  create:
+  Create-Issue:
     runs-on: ubuntu-latest
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: REST API create issue
         run: |
-          curl -L \
+          if curl -L --fail\
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ github.token }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-              https://api.github.com/repos/${{ github.repository }}/issues \
-              -d '{"title":"Test 1","body":"Testing 123","labels":["bug"]}'
+              https://api.github.com/repos/kierramarie/${{ github.repository }}/issues \
+              -d '{"title":"Test 1","body":"Testing 123","labels":["bug"]}'; then
+              echo "Issue successfully created"
+          else
+              echo "Issue creation failed"
+              exit 1
+          fi
